export const SEO_KEYWORDS = {
  en: {
    imageLeaks: 'image leaks',
    videoLeaks: 'video leaks',
    leaked: 'leaked',
    exclusive: 'exclusive content',
    photos: 'photos',
    videos: 'videos',
    collection: 'collection',
    download: 'download',
    getLink: 'get link',
    free: 'free',
    pack: 'pack',
    zip: 'zip',
    mega: 'mega link',
    archive: 'archive',
    fullSet: 'full set',
    nsfw: 'NSFW',
    uncensored: 'uncensored',
    exposed: 'exposed',
    premium: 'premium content'
  },
  es: {
    imageLeaks: 'fotos filtradas',
    videoLeaks: 'videos filtrados',
    leaked: 'filtrado',
    exclusive: 'contenido exclusivo',
    photos: 'fotos',
    videos: 'videos',
    collection: 'colección',
    download: 'descargar',
    getLink: 'obtener enlace',
    free: 'gratis',
    pack: 'paquete',
    zip: 'zip',
    mega: 'enlace mega',
    archive: 'archivo',
    fullSet: 'conjunto completo',
    nsfw: 'NSFW',
    uncensored: 'sin censura',
    exposed: 'expuesto',
    premium: 'contenido premium'
  },
  fr: {
    imageLeaks: 'photos divulguées',
    videoLeaks: 'vidéos divulguées',
    leaked: 'divulgué',
    exclusive: 'contenu exclusif',
    photos: 'photos',
    videos: 'vidéos',
    collection: 'collection',
    download: 'télécharger',
    getLink: 'obtenir le lien',
    free: 'gratuit',
    pack: 'pack',
    zip: 'zip',
    mega: 'lien mega',
    archive: 'archive',
    fullSet: 'ensemble complet',
    nsfw: 'NSFW',
    uncensored: 'non censuré',
    exposed: 'exposé',
    premium: 'contenu premium'
  },
  de: {
    imageLeaks: 'durchgesickerte Bilder',
    videoLeaks: 'durchgesickerte Videos',
    leaked: 'durchgesickert',
    exclusive: 'exklusiver Inhalt',
    photos: 'Fotos',
    videos: 'Videos',
    collection: 'Sammlung',
    download: 'herunterladen',
    getLink: 'Link erhalten',
    free: 'kostenlos',
    pack: 'Paket',
    zip: 'Zip',
    mega: 'Mega-Link',
    archive: 'Archiv',
    fullSet: 'vollständiges Set',
    nsfw: 'NSFW',
    uncensored: 'ungefiltert',
    exposed: 'enthüllt',
    premium: 'Premium-Inhalt'
  },
  ru: {
    imageLeaks: 'утечка изображений',
    videoLeaks: 'утечка видео',
    leaked: 'слито',
    exclusive: 'эксклюзивный контент',
    photos: 'фотографии',
    videos: 'видео',
    collection: 'коллекция',
    download: 'скачать',
    getLink: 'получить ссылку',
    free: 'бесплатно',
    pack: 'пакет',
    zip: 'zip',
    mega: 'mega ссылка',
    archive: 'архив',
    fullSet: 'полный набор',
    nsfw: 'NSFW',
    uncensored: 'без цензуры',
    exposed: 'обнажённый',
    premium: 'премиум контент'
  },
  zh: {
    imageLeaks: '照片泄露',
    videoLeaks: '视频泄露',
    leaked: '泄露',
    exclusive: '独家内容',
    photos: '照片',
    videos: '视频',
    collection: '合集',
    download: '下载',
    getLink: '获取链接',
    free: '免费',
    pack: '打包',
    zip: '压缩包',
    mega: 'mega链接',
    archive: '档案',
    fullSet: '完整套装',
    nsfw: 'NSFW',
    uncensored: '未删减',
    exposed: '曝光',
    premium: '高级内容'
  },
  ja: {
    imageLeaks: '画像リーク',
    videoLeaks: '動画リーク',
    leaked: 'リークされた',
    exclusive: '独占コンテンツ',
    photos: '写真',
    videos: '動画',
    collection: 'コレクション',
    download: 'ダウンロード',
    getLink: 'リンク取得',
    free: '無料',
    pack: 'パック',
    zip: 'zip',
    mega: 'megaリンク',
    archive: 'アーカイブ',
    fullSet: 'フルセット',
    nsfw: 'NSFW',
    uncensored: '無修正',
    exposed: '暴露',
    premium: 'プレミアムコンテンツ'
  },
  pt: {
    imageLeaks: 'fotos vazadas',
    videoLeaks: 'vídeos vazados',
    leaked: 'vazado',
    exclusive: 'conteúdo exclusivo',
    photos: 'fotos',
    videos: 'vídeos',
    collection: 'coleção',
    download: 'baixar',
    getLink: 'obter link',
    free: 'grátis',
    pack: 'pacote',
    zip: 'zip',
    mega: 'link mega',
    archive: 'arquivo',
    fullSet: 'conjunto completo',
    nsfw: 'NSFW',
    uncensored: 'sem censura',
    exposed: 'exposto',
    premium: 'conteúdo premium'
  },
  it: {
    imageLeaks: 'immagini trapelate',
    videoLeaks: 'video trapelati',
    leaked: 'trapelato',
    exclusive: 'contenuto esclusivo',
    photos: 'foto',
    videos: 'video',
    collection: 'collezione',
    download: 'scarica',
    getLink: 'ottieni link',
    free: 'gratis',
    pack: 'pacchetto',
    zip: 'zip',
    mega: 'link mega',
    archive: 'archivio',
    fullSet: 'set completo',
    nsfw: 'NSFW',
    uncensored: 'non censurato',
    exposed: 'esposto',
    premium: 'contenuto premium'
  },
  ko: {
    imageLeaks: '유출 이미지',
    videoLeaks: '유출 비디오',
    leaked: '유출됨',
    exclusive: '독점 콘텐츠',
    photos: '사진',
    videos: '비디오',
    collection: '컬렉션',
    download: '다운로드',
    getLink: '링크 받기',
    free: '무료',
    pack: '팩',
    zip: 'zip',
    mega: 'mega 링크',
    archive: '아카이브',
    fullSet: '전체 세트',
    nsfw: 'NSFW',
    uncensored: '검열 해제',
    exposed: '노출됨',
    premium: '프리미엄 콘텐츠'
  }
};

export const generateSEOTitle = (modelName, type = 'both', lang = 'en') => {
  const keywords = SEO_KEYWORDS[lang] || SEO_KEYWORDS.en;

  if (type === 'image') {
    return `${modelName} ${keywords.imageLeaks} ${keywords.fullSet} - ${keywords.exclusive} ${keywords.photos} ${keywords.download} ${keywords.getLink} ${keywords.free}`;
  } else if (type === 'video') {
    return `${modelName} ${keywords.videoLeaks} ${keywords.fullSet} - ${keywords.exclusive} ${keywords.videos} ${keywords.download} ${keywords.getLink} ${keywords.free}`;
  }
  return `${modelName} ${keywords.imageLeaks} & ${keywords.videoLeaks} ${keywords.fullSet} - ${keywords.exclusive} ${keywords.collection} ${keywords.download} ${keywords.getLink} ${keywords.free}`;
};

export const generateSEODescription = (
  modelName,
  imageCount,
  videoCount,
  lang = 'en'
) => {
  const keywords = SEO_KEYWORDS[lang] || SEO_KEYWORDS.en;
  return `${keywords.exclusive} ${modelName} ${keywords.leaked} ${keywords.collection}. ${imageCount} ${keywords.photos} and ${videoCount} ${keywords.videos} available. Latest ${modelName} ${keywords.imageLeaks}, ${keywords.videoLeaks}, ${keywords.fullSet}, ${keywords.zip}, ${keywords.download}, ${keywords.nsfw}, ${keywords.uncensored}, ${keywords.exposed}, ${keywords.mega}, ${keywords.archive}, ${keywords.getLink}, ${keywords.free}.`;
};
